version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - run:
          name: Test Node
          command: node -v
#      - run:
#          name: Lighthouse Report
#          command: lighthouse https://airhorner.com/ --chrome-flags="--headless" --config-path=lighthouse-config.json --output=json --output-path=lighthouse-report.json
